version: '3.7'

services:
  swapi:
    build:
      context: .
      dockerfile: Dockerfile.swapi
    # TODO: remove - debug only
    ports:
      - 8001:8000

  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-pass
    volumes:
      # keep db data between startups
      - db_data:/var/lib/postgresql/data

  backend:
    env_file:
      - env.local
    image: adv-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # for code hot-reloading
      - .:/code:delegated
      # keep requirements between startups
      - python_lib:/usr/local/lib/python3.7
      # keep datasets
      - datasets:/datasets
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - swapi
    command: >-
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  ui:
    image: adv-ui
    environment:
      - BACKEND_URL=http://localhost:8000
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./ui:/code:delegated
      - node_modules:/code/node_modules
    depends_on:
      - backend
    command: yarn serve


# Persisted or shared between runs
volumes:
  db_data:
  python_lib:
  node_modules:
  datasets:
